### ISSUE TITLE
Allow for DeleteProfilesOlderThan to be set to 0

### ISSUE THREAD

**Issue by han44-illinois** [engrit-illinois/Remove-LocalUserProfiles#2] opened 2022-04-06 22:59 UTC
On some computers, and seemingly with higher frequency on those computers with close to zero disk space left, having a minimum value of 1 for the DeleteProfilesOlderThan variable returns zero eligible profiles to be deleted. Whatever property it's looking at appears to be modified very frequently especially on computers with 0 disk space (Just speculating, but maybe the OS is touching each profile for compression or something).

If possible, it'd be great if we could specify 0 for this value so we can just ignore the age entirely. This would of course open us up to potentially wiping every profile on a given computer, but is useful in the scenario where we rely solely on the ExcludedUsers while performing some profile cleanup.

**Comment by mmseng** [comment] 2022-04-08 21:28
Yeah, the profiles getting touched all the time by Windows is the root cause of the unreliability issue, noted in the [Context](https://github.com/engrit-illinois/Remove-LocalUserProfiles#context) section of the readme.

I'm happy to accommodate for the use case of wiping all profiles, regardless of age, but I'll need to re-learn how the profile age works again to make sure I'm doing it right.

Also I realize now that I started overhauling this module to work asynchronously, and never finished that, so I'll work on the minimum age fix alongside finishing up the new version.

In the meantime, if you want, you can edit your copy of the current script. Currently it's just a hard check for whether the value of `-DeleteProfilesOlderThan` is less than 1, on line 67. This can be changed to 0, or the check can be removed entirely, by removing lines 67-70, and line 201.

**Comment by mmseng** [comment] 2023-10-31 20:06
Resolved in https://github.com/engrit-illinois/Remove-LocalUserProfiles/commit/43655a3a48745569b89843880c44eb69b94b5966

**Closed as completed by mmseng** 2023-10-31 20:06 UTC
